baseURL: https://stevenbrok.netlify.app
languageCode: en-us
theme: raditian-free-hugo-theme
params:
  title: "Stefan Musch | Data Scienctist"
  footer:
    copyright: © Stefan Musch. All rights reserved.
    # radity_logo:
    #   _2x: img/general/bbb_favicon.png
    #   alt: Design & Code - Radity
    #   x: img/logos/bbb_favicon.png
  googleTagManagerID: GTM-000000
  logo:
    image1: img/logos/bbb_main.png
    image2: img/logos/favicon.ico
    text1: Stefan
    text2: Musch
  plugins:
    css:
      - URL: css/main.css
      - URL: css/rad-icons.css
      - URL: css/custom.css
    js:
      - URL: js/rad-animations.js
      - URL: js/sticky-header.js
      - URL: js/library/fontfaceobserver.js
  sections:
    - showcase
    - about
    - education
    - experience
    - client-and-work
    - testimonial
    - contact
    - newsletter
menu:
  footer:
    - URL: '#about'
      name: About
      weight: 2
    - URL: '#portfolio'
      name: Portfolio
      weight: 3
    - URL: '#contact'
      name: Contact
      weight: 4
  header:
    - URL: '#about'
      name: About
      weight: 2
    - URL: '#portfolio'
      name: Portfolio
      weight: 3
    - URL: '#contact'
      name: Contact
      weight: 4
